### ISSUE TITLE
[SETTING] Docker compose 세팅 및 db 세팅

### ISSUE THREAD

**Issue by imjanghyeok** [wakeup0105/Backend#15]
## 제목
Docker compose 세팅 및 db 세팅

### TODO
- [x] docker를 이용해서 server와 db 컨테이너 구현
- [x] docker compose를 이용해서 통합 환경 구축
- [x] CI/CD 구축할 수 있도록 Flow 지정
- [x] 성능 테스트를 위한 세팅

### 참고 할만한 자료
https://velog.io/@appti/docker-compose-Springboot-Postgresql-Redis-kf8v2esn
https://www.baeldung.com/spring-boot-postgresql-docker
