### ISSUE TITLE
[FEATURE] MemberInfo Entity 작성

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#19]
## 제목
MemberInfo Entity를 작성합니다.

### TODO
- [x] MemberInfo Entity 작성
- [x] MemberInfoId 복합키 정의 작성
- [x] Member Entity에 관계 추가
- [x] h2-console 경로 허용
- [x] Test
