### ISSUE TITLE
[FEATURE] 닉네임 설정 구현

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#23]
## 제목
닉네임을 설정하여 DB에 저장하도록 구현합니다.

### TODO
- [x] 회원가입 후 바로 로그인 되도록 변경
- [x] SetNicknameRequestDTO 작성
- [x] MemberInfo Entity nickname 필드 길이 2-30으로 설정
- [x] MemberInfo Controller에 POST 요청으로 닉네임 설정 api 구현
- [x] MemberInfo Service에 닉네임 설정 로직 구현
- [x] MemberInfo Repository 생성
- [x] MemberInfo Controller에 GET 요청으로 유저 정보 불러오기 api 구현
- [x] TEST
