### ISSUE TITLE
[FEATURE] 나의 정보 관리 페이지 기능 개발

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#26]
## 제목
나의 정보 관리 페이지에 필요한 기능을 개발합니다.

### TODO
- [x] 응답에 사용될 ReponseDTO 생성
- [x] 필요한 정보를 돌려주는 GET 요청인 API 작성
- [x] 이메일 인증시 JWT 토큰을 발급하도록 변경
- [x] 비밀번호 변경 요청시 토큰에서 유저 email을 가져오도록 변경
- [x] Test
