### ISSUE TITLE
[FEATURE] Member Entity 작성

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#3]
## 제목
Member Entity 작성

### TODO
- [x] pk 필드 작성
- [x] email 필드 작성
- [x] password 필드 작성
- [x] point 필드 작성
