### ISSUE TITLE
[FEATURE] Avatar Entity들 개발 

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#32]
## 제목
사용자의 눈 아바타 소유 목록인 OwnAvatar Entity와 관련하여 기능 개발
테이블명만 다를 뿐 기능은 같기에 동시에 개발

### TODO
- [x] eyes, mouth, head, body Entity 작성
- [x] 각각의 OwnAvatar Entity 작성
- [x] 각각의 전체조회 DTO 및 변환 클래스 작성
- [x] 각각 Character Entity와 1:N관계 연결 ( Character : OwnAvatar )
- [x] 각각의 OwnAvatar Repository 작성
- [x] 각각의 OwnAvatar Service 작성
- [x] 각각의 OwnAvatar Controller 작성
- [x] Test
