### ISSUE TITLE
[FEATURE] 장식 구매 및 착용 구현

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#34]
## 제목
커스터마이징 장식을구매하고 착용하는 로직을 구현합니다.

### TODO
- [x] 각 부위별 Repository 작성
- [x] OwnAvatar Repository에 중복 방지 조회 추가
- [x] OwnAvatar에 구매 Dto와 Service 작성
- [x] Character Controller에 구매 api 추가
- [x] Character 장식 착용 DTO 작성
- [x] Character Service 작성
- [x] Test
