### ISSUE TITLE
[FEATURE] 한 줄 소개 기능 개발

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#35]
## 제목
한 줄 소개 기능을 개발합니다.

### TODO
- [x] Entity에 필드 추가
- [x] dto 생성 및 변환 클래스 추가 그리고 적용
- [x] 한 줄 소개 변경 DTO 추가
- [x] Service 작성
- [x] Controller 작성
- [x] Test
