### ISSUE TITLE
[FEATURE] PUT 요청 -> PATCH로 변경

### ISSUE THREAD

**Issue by congachu** [wakeup0105/Backend#38]
## 제목
일부 데이터를 수정하는 것에서 PATCH가 더 적합하다 생각하여 변경합니다.

### TODO
- [x] 비밀번호 변경 요청 PATCH로 변경
- [x] 닉네임 설정 PATCH로 변경
- [x] 자기소개 설정 PATCH로 변경
- [x] Test
