### ISSUE TITLE
[FEATURE] 알람 확인 및 스트레칭 성공시 데이터 변경 및 저장

### ISSUE THREAD

**Issue by imjanghyeok** [wakeup0105/Backend#44]
### TODO
- [x] 성공 시, 성공 카운트 증가
- [x] 성공 시, exp 증가
- [x] 성공 시, point 증가
- [x] 실패 시, 실패 카운트 증가
- [x] exp 기준 충족 시, 레벨 업
